spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234567890
    url: jdbc:mysql://localhost:3306/es_blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.sanshi.searchforblog.entity


server:
  port: 8080

